spring.application.name=importer
spring.datasource.url=jdbc:postgresql://localhost:5432/importer_db
spring.datasource.username=${username}
spring.datasource.password=${password}
apiToken=${API_TOKEN}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=false
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:mapper/**/*.xml
#local-path=src/main/resources/Hojinjoho_20260302
local-path=src/main/resources/temporary
#local-path=src/main/resources/full
app.importer.url=https://info.gbiz.go.jp/hojin/Download
node.id = Mihaela's Server
exporter.batch.size = 50
warehouse.base-url=http://localhost:8081
jobs.import.delay=300000
jobs.export.not-before=08:55:00
jobs.orchestrator.delay = 6000


data.source=REMOTE

pipeline.import.lease.seconds=120
pipeline.export.lease.seconds=120

exporter.thread.count=4

importer.max-attempts=3