spring.application.name=importer
spring.datasource.url=jdbc:postgresql://localhost:5432/importer_db
spring.datasource.username=${username}
spring.datasource.password=${password}
apiToken=${API_TOKEN}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=false
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:mapper/**/*.xml
#local-path=src/main/resources/Hojinjoho_20260306
local-path=src/main/resources/test
app.importer.url=https://info.gbiz.go.jp/hojin/Download
instance.id = Mihaela's Server
exporter.batch.size = 500
warehouse.base-url=http://localhost:8081
jobs.import.delay=300000
jobs.export.cron=0 0 22 * * *

data.source = local