spring.application.name=importer
node.id=Mihaela's Server
spring.datasource.url=jdbc:postgresql://localhost:5432/importer_db
spring.datasource.username=${username}
spring.datasource.password=${password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=false
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:mapper/**/*.xml
exporter.security.username=${API_USERNAME:admin}
exporter.security.password=${API_PASSWORD:admin123}
warehouse.base-url=http://localhost:8081
pipeline.export.lease.seconds=120
exporter.batch.size=100
exporter.thread.count=4
exporter.max-attempts=3
importer.max-attempts=3
app.security.username=${EXECUTOR_USERNAME:admin}
app.security.password=${EXECUTOR_PASSWORD:admin123}

